-- DASTYOR AI — Supabase minimal production schema
-- Run in SQL Editor (once). Service role / server uses SUPABASE_SERVICE_ROLE_KEY.

-- Users: id = Telegram user id (bigint)
create table if not exists public.users (
  id bigint primary key,
  first_name text default '',
  username text default '',
  chat_id bigint,
  joined_at timestamptz default now(),
  last_active timestamptz,
  activity_count int default 0,
  files_processed int default 0,
  sessions int default 0,
  lang text default 'uz_lat',
  is_banned boolean default false,
  ban_reason text,
  ban_date timestamptz,
  blocked_bot boolean default false,
  last_service text,
  user_plan text default 'standard',
  usage_count int default 0,
  limit_count int,
  daily_limit int default 10,
  used_count int default 0
);

create index if not exists idx_users_user_plan on public.users (user_plan);
create index if not exists idx_users_last_active on public.users (last_active desc);

-- Action audit (OCR, CV, PDF, imlo, …)
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  action_type text not null,
  file_name text,
  metadata jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_logs_user_id on public.logs (user_id);
create index if not exists idx_logs_created_at on public.logs (created_at desc);
create index if not exists idx_logs_action on public.logs (action_type);

-- Daily usage (kunlik limit)
create table if not exists public.daily_usage (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  usage_date date not null,
  count int not null default 0,
  unique (user_id, usage_date)
);

-- Optional: generic usage_logs (code falls back here)
create table if not exists public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  action text not null,
  metadata jsonb,
  created_at timestamptz default now()
);

-- Bot settings singleton
create table if not exists public.bot_settings (
  id int primary key default 1,
  daily_limit int default 10,
  maintenance_mode boolean default false
);

insert into public.bot_settings (id, daily_limit, maintenance_mode)
values (1, 10, false)
on conflict (id) do nothing;

-- Premium subscriptions (admin tasdiq)
create table if not exists public.premium_subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  plan_type text not null default 'premium',
  start_date timestamptz,
  end_date timestamptz,
  expire_date timestamptz,
  status text default 'active'
);

-- Payments / skrinshotlar
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  plan_type text not null,
  amount numeric,
  currency text default 'UZS',
  screenshot_url text,
  status text default 'pending',
  metadata jsonb,
  reviewed_by bigint,
  admin_note text,
  created_at timestamptz default now()
);

-- RLS: backend uses service role — policies ixtiyoriy (anon o‘chiq qoling).
alter table public.users enable row level security;
alter table public.logs enable row level security;

-- Service role bypasses RLS; anon uchun hech narsa qo‘ymasangiz ham bo‘ladi.
