-- =============================================================================
-- DIQQAT
-- Agar Supabase-da allaqachon "users", "logs", "payments" kabi jadvallar BOR bo'lsa,
-- U SHU FAYLNI ISHLATMANG — xato yoki dublikat bo'ladi.
-- O'rniga: migrate_safe_for_existing_db.sql ni ishga tushiring.
--
-- Bu fayl: to'liq bo'sh / yangi loyiha uchun yoki reference sifatida.
-- =============================================================================

-- Users: id = Telegram user id (bigint)
CREATE TABLE IF NOT EXISTS public.users (
  id bigint PRIMARY KEY,
  first_name text DEFAULT '',
  username text DEFAULT '',
  chat_id bigint,
  joined_at timestamptz DEFAULT now(),
  last_active timestamptz,
  activity_count int DEFAULT 0,
  files_processed int DEFAULT 0,
  sessions int DEFAULT 0,
  lang text DEFAULT 'uz_lat',
  is_banned boolean DEFAULT false,
  ban_reason text,
  ban_date timestamptz,
  blocked_bot boolean DEFAULT false,
  last_service text,
  user_plan text DEFAULT 'standard',
  usage_count int DEFAULT 0,
  limit_count int,
  daily_limit int DEFAULT 10,
  used_count int DEFAULT 0,
  pending_oby_json jsonb,
  pending_oby_updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_users_user_plan ON public.users (user_plan);
CREATE INDEX IF NOT EXISTS idx_users_last_active ON public.users (last_active DESC);

CREATE TABLE IF NOT EXISTS public.logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  action_type text NOT NULL,
  file_name text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_logs_user_id ON public.logs (user_id);
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON public.logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_logs_action ON public.logs (action_type);

CREATE TABLE IF NOT EXISTS public.daily_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  usage_date date NOT NULL,
  count int NOT NULL DEFAULT 0,
  UNIQUE (user_id, usage_date)
);

CREATE TABLE IF NOT EXISTS public.usage_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  action text NOT NULL,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.bot_settings (
  id int PRIMARY KEY DEFAULT 1,
  daily_limit int DEFAULT 10,
  maintenance_mode boolean DEFAULT false
);

INSERT INTO public.bot_settings (id, daily_limit, maintenance_mode)
VALUES (1, 10, false)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.premium_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  plan_type text NOT NULL DEFAULT 'premium',
  start_date timestamptz,
  end_date timestamptz,
  expire_date timestamptz,
  status text DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  plan_type text NOT NULL,
  amount numeric,
  currency text DEFAULT 'UZS',
  screenshot_url text,
  status text DEFAULT 'pending',
  metadata jsonb,
  reviewed_by bigint,
  admin_note text,
  created_at timestamptz DEFAULT now()
);

-- RLS (ixtiyoriy): service role RLS dan o'tadi
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
