class WaitingState:
    OCR_IMAGE = "ocr_image"
    OCR_IMAGE_DOC = "ocr_image_doc"
    TRANSLITERATE_TEXT = "transliterate_text"
    TRANSLIT_CONTENT = "translit_content"
    TRANSLATE_INPUT = "translate_input"
    SPELL_CHECK_DOC = "spell_check_doc"
    SPELLCHECK_FILE = "spellcheck_file"
    PDF_IMAGES = "pdf_images"
    FEEDBACK = "feedback"
    OBYEKTIVKA_AUDIO = "obyektivka_audio"
    TRANSLATE_FILE = "translate_file"
    TRANSLIT_FILE = "translit_file"
    PREMIUM_PAYMENT_SCREENSHOT = "premium_payment_screenshot"
